apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer
  name: consumer-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers: 
        - image: braydenwongcode/socialbutterfly-consumer:latest
          name: consumer-server
          ports:
          - containerPort: 3002