apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka
  name: eureka-svc
spec:
  ports:
  - name: eureka-discovery
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: eureka
status:
  loadBalancer: {}