apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eureka
  name: eureka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - image: braydenwongcode/socialbutterfly-eureka:latest
          name: eureka-server
          ports:
            - containerPort: 8761