apiVersion: v1
kind: PersistentVolumeClaim        # Create a PersistentVolumeClaim to request a PersistentVolume storage
metadata:                          # Claim name and labels
  name: mongo-db-claim
  labels:
    app: socialbutterfly
spec:                              # Access mode and resource limits
  accessModes:
    - ReadWriteOnce                # ReadWriteOnce means the volume can be mounted as read-write by a single Node
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1  # API version
kind: Service # Type of kubernetes resource
metadata:
  name: socialbutterfly  # Name of the resource
  labels:   # Labels that will be applied to the resource
    app: socialbutterfly
spec:
  ports:
  - port: 27017
  selector:   # Selects any Pod with labels `app=mongo-db-app,tier=mongo`
    app: socialbutterfly
    tier: mongo
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment                    # Type of the kubernetes resource
metadata:
  name: socialbutterfly
  labels:                           # Labels applied to this deployment
    app: socialbutterfly
spec:
  selector:
    matchLabels:                    # This deployment applies to the Pods matching the specified labels
      app: socialbutterfly
      tier: mongo
  strategy:
    type: Recreate
  template:                         # Template for the Pods in this deployment
    metadata:
      labels:
        app: socialbutterfly
        tier: mongo
    spec:
      containers:
        - image: mongo:latest
          name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_DATABASE
              value: Docusign
            - name: MONGO_DB_USERNAME
              value: test
            - name: MONGO_DB_PASSWORD
              value: test
          ports:
            - containerPort: 27017        # The port that the container exposes
              name: mongo
          volumeMounts:
            - mountPath: /var/lib/mongo
              name: mongo-db-claim
      restartPolicy: Always
      volumes:
        - name: mongo-db-claim
          persistentVolumeClaim:
            claimName: mongo-db-claim
