apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer
  name: consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer-server
          image: braydenwongcode/socialbutterfly-consumer:latest
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  selector:
    app: consumer
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002