apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: events
  name: events-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
        - name: users-server
          image: braydenwongcode/socialbutterfly-events:latest
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: events
spec:
  selector:
    app: events
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001