apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-server
          image: braydenwongcode/socialbutterfly-users:latest
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    app: users
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000