apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: events
  name: events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events
  strategy: {}
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
      - image: braydenwongcode/socialbutterfly-events:latest
        name: socialbutterfly-events
        resources: {}
        livenessProbe:
          httpGet: 
            path: /livenessCheck
            port: 3001
        readinessProbe:
          httpGet:
            path: /livenessCheck
            port: 3001
        ports:
        - name: http
          containerPort: 3001
status: {}
