apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: events
  name: events-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
      - image: braydenwongcode/socialbutterfly-events:latest
        name: events-server
        ports:
        - name: http
          containerPort: 3001