apiVersion: v1
kind: Deployment
metadata:
  name: event-deployment
  labels:
    app: event
spec:
  replicas: 1
  template:
    metadata: 
      labels:
        app: event
    spec:
      containers:
      - name: event-api
        image: braydenwongcode/socialbutterfly-event:latest
        ports:
        - containerPort: 3001
        resources:
          limits:
            memory: 512Mi
            cpu: 1
          requests:
            memeory: 256Mi
            cpu: 0.2
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
