apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users
  name: users-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - image: braydenwongcode/socialbutterfly-users:latest
        name: user-server
        ports:
        - containerPort: 3000